name: Next.js 15 CI/CD Pipeline

on:
  push:
    branches: [ main, feature/test-automation ]
  pull_request:
    branches: [ main ]

env:
  NODE_VERSION: '20'
  NEXT_TELEMETRY_DISABLED: 1

jobs:
  # Lint and Type Check
  lint-and-type-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: |
          cd alexai-nextjs-modern
          npm ci

      - name: Run ESLint
        run: |
          cd alexai-nextjs-modern
          npm run lint

      - name: Type check
        run: |
          cd alexai-nextjs-modern
          npx tsc --noEmit

  # Build and Test
  build-and-test:
    runs-on: ubuntu-latest
    needs: lint-and-type-check
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: |
          cd alexai-nextjs-modern
          npm ci

      - name: Build application
        run: |
          cd alexai-nextjs-modern
          npm run build

      - name: Run tests (if available)
        run: |
          cd alexai-nextjs-modern
          npm test --if-present

  # Deploy to Vercel (Production)
  deploy-production:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main'
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Deploy to Vercel
        run: |
          cd alexai-nextjs-modern
          vercel --prod --token ${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

  # Deploy to Vercel (Preview)
  deploy-preview:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref != 'refs/heads/main'
    environment: preview
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Deploy to Vercel (Preview)
        run: |
          cd alexai-nextjs-modern
          vercel --token ${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

  # Security Scan
  security-scan:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run security audit
        run: |
          cd alexai-nextjs-modern
          npm audit --audit-level moderate

  # Performance Test
  performance-test:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: |
          cd alexai-nextjs-modern
          npm ci

      - name: Start Next.js server
        run: |
          cd alexai-nextjs-modern
          npm run build
          npm start &
          sleep 10

      - name: Run Lighthouse CI
        run: |
          npm install -g @lhci/cli@0.12.x
          lhci autorun
        working-directory: alexai-nextjs-modern

  # Notify on Success
  notify-success:
    runs-on: ubuntu-latest
    needs: [deploy-production, security-scan, performance-test]
    if: success() && github.ref == 'refs/heads/main'
    steps:
      - name: Notify deployment success
        run: |
          echo "🚀 Modern Next.js 15 deployment successful!"
          echo "Production URL: https://alexai-nextjs-modern.vercel.app"
          echo "LCARS Design System: ✅ Active"
          echo "TypeScript: ✅ Compiling"
          echo "Performance: ✅ Optimized"

  # Notify on Failure
  notify-failure:
    runs-on: ubuntu-latest
    if: failure()
    steps:
      - name: Notify deployment failure
        run: |
          echo "❌ Deployment failed!"
          echo "Please check the logs for details."
          echo "Branch: ${{ github.ref }}"
          echo "Commit: ${{ github.sha }}" 